# Test Dice 2022-10-18 at 18:17:07

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        perl lib/Dice.pm
        prove -Ilib t/
