# Test Dice 2022-10-18 at 18:27:44

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download other repos
      run: |
        curl -sL https://github.com/philiprbrenan/DataTableText/archive/refs/heads/main.zip > DataTableText.zip
        unzip DataTableText
        cp -R DataTableText-main/* .
        tree

    - name: Install Test::Most
      run: |
        sudo cpan install -T Test::Most

    - name: Install Data::Dump
      run: |
        sudo cpan install -T Data::Dump

    - name: Test
      run: |
        perl  -Ilib lib/Dice.pm
        prove -Ilib t/
